spring:
  application:
    name: hanwol

server:
  port: ${PORT:8080}

  # 데이터베이스 접속 설정
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hanwol?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA (Hibernate) 설정
  jpa:
    hibernate:
      # 초기 개발 단계이므로 엔티티 기반으로 테이블 자동 생성 (update)
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # 뷰 템플릿(Thymeleaf) 설정
  thymeleaf:
    cache: false # 개발 중엔 캐시 끄기 (수정사항 즉시 반영)
    prefix: classpath:/templates/
    suffix: .html

  # 메일 발송 (SMTP) 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:gksxogksxo1001@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:vsqv rpeo wrnn vqlm}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 로깅 설정
logging:
  level:
    root: INFO
    com.hanwol: DEBUG # 우리 프로젝트 패키지는 자세히 보기
    org.hibernate.SQL: DEBUG # SQL 쿼리 자세히 보기
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # 쿼리 파라미터 값 보기
